if(NOT CMAKE_CROSSCOMPILING)
  find_package(PkgConfig QUIET)
  pkg_check_modules(PC_LIBGIT2 libgit2)
endif()

set_extra_dirs_lib(LIBGIT2 libgit2)
find_library(LIBGIT2_LIBRARY
  NAMES git2
  HINTS ${HINTS_LIBGIT2_LIBDIR} ${PC_LIBGIT2_LIBDIR} ${PC_LIBGIT2_LIBRARY_DIRS}
  PATHS ${PATHS_LIBGIT2_LIBDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
set_extra_dirs_include(LIBGIT2 libgit2 "${LIBGIT2_LIBRARY}")
find_path(LIBGIT2_INCLUDEDIR git2.h
  HINTS ${HINTS_LIBGIT2_INCLUDEDIR} ${PC_LIBGIT2_INCLUDEDIR} ${PC_LIBGIT2_INCLUDE_DIRS}
  PATHS ${PATHS_LIBGIT2_INCLUDEDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Libgit2 DEFAULT_MSG LIBGIT2_LIBRARY LIBGIT2_INCLUDEDIR)

mark_as_advanced(LIBGIT2_LIBRARY LIBGIT2_INCLUDEDIR)

if(LIBGIT2_FOUND)
  is_bundled(LIBGIT2_BUNDLED "${LIBGIT2_LIBRARY}")
  set(LIBGIT2_LIBRARIES ${LIBGIT2_LIBRARY})
  set(LIBGIT2_INCLUDE_DIRS ${LIBGIT2_INCLUDEDIR})
  set(LIBGIT2_COPY_FILES)
endif()
